### ISSUE TITLE
Namespace

### ISSUE THREAD

**Issue by diegobrum** [dalenewman/DateMath#2]
**What**
Change namespace from **"dalenewman"** to **"DaleNewMan"** (or some thing like this)

**Why**
namespaces convention (https://msdn.microsoft.com/en-us/library/ms229026(v=vs.110).aspx)

**Comment by dalenewman** [comment]
I am thinking `DaleNewman` since *Newman* is one word.  Do you think I should add a second level for the  *Product|Technology* part? I am thinking since DateMath is a static class, it kind of serves that role.

Your thoughts?

Thanks

**Comment by diegobrum** [comment]
**DaleNewman** it's great!

DateMath it's a simple class and I think that this project won't grow up a lot.
Namespace with just one level it's fine for me :)

Tks

**Comment by dalenewman** [comment]
Ok I'll push changes after lunch.  Thanks for your help :-)
